# Generated by Django 5.2.5 on 2025-08-26 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThoughtEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='或许是标题', max_length=200)),
                ('date', models.DateField(help_text='应该是日期')),
                ('content', models.TextField(help_text='有什么想说的就写下来吧')),
                ('is_public', models.BooleanField(default=False, help_text='要不要公开呢？')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, help_text='日志作者，空表示匿名', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thought_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '日志条目',
                'verbose_name_plural': '日志条目列表',
                'ordering': ['-date'],
            },
        ),
    ]
