# Generated by Django 5.2.5 on 2025-08-27 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='thoughtentry',
            name='author',
            field=models.ForeignKey(blank=True, help_text='留名于此，空白则为匿名', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thought_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thoughtentry',
            name='date',
            field=models.DateField(help_text='写下文字的时刻'),
        ),
        migrations.AlterField(
            model_name='thoughtentry',
            name='title',
            field=models.CharField(help_text='或许有总结', max_length=200),
        ),
        migrations.CreateModel(
            name='MessageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='留言内容')),
                ('is_public', models.BooleanField(default=False, help_text='要不要公开呢？')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, help_text='留名于此', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言列表',
                'ordering': ['-timestamp'],
            },
        ),
    ]
